name: NormalContrast
version: 0.0.1
synopsis: Light color scheme generator
description: See README
maintainer: Alexey Kotlyarov <a@koterpillar.com>

default-extensions:
- OverloadedStrings
- RecordWildCards

executable:
  main: Main.hs
  source-dirs: .
  dependencies:
    - base
    - aeson
    - aeson-pretty
    - bytestring
    - containers
    - optparse-applicative
    - split
    - terminal-size
    - text
    - utf8-string
    - uuid
    - xml-conduit
